[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
)/
'''

[tool.isort]
profile = "black"

[tool.pylint]  # If you opt to use pylint
# Pylint configuration options

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
